# Generated by Django 4.2.1 on 2023-05-05 20:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('employee_no', models.IntegerField(unique=True, validators=[django.core.validators.MaxLengthValidator(4, 'Employee No have to be 4 digits'), django.core.validators.MinLengthValidator(4, 'Employee No have to be 4 digits')])),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('Employee', 'Employee')], default='Admin')),
                ('password', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(6, 'Password must contain at least 6 characters')])),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
