# Generated by Django 4.2.1 on 2023-05-05 23:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='employee_no',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=400, validators=[django.core.validators.MinLengthValidator(6, 'Password must contain at least 6 characters')]),
        ),
    ]
