# Generated by Django 4.2.1 on 2023-05-06 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_app', '0005_alter_user_employee_no_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reservation_date', models.DateField()),
                ('starting_time', models.TimeField()),
                ('ending_time', models.TimeField()),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', default=None, on_delete=django.db.models.deletion.PROTECT, related_name='reserved_by', to=settings.AUTH_USER_MODEL)),
                ('table', models.ForeignKey(db_column='table_id', default=None, on_delete=django.db.models.deletion.PROTECT, related_name='table', to='reservation_app.table')),
            ],
            options={
                'db_table': 'reservations',
            },
        ),
    ]
