# Generated by Django 4.2.1 on 2023-05-06 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_app', '0007_alter_reservation_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reservation_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
