# Generated by Django 4.2.1 on 2023-05-06 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_app', '0008_alter_reservation_reservation_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='reservation_date',
            new_name='reserved_at',
        ),
    ]
